Update Compose and others
romainguy/sample-wake-me-up pull request #5
Opened 2022-11-05 07:51 UTC by djnotes

Compose to 1.3.0
Filament to  1.28.2
Android Gradle plugin to 8.0.0-alpha07
Kotlin Gradle plugin to 1.7.10
Gradle to 7.5
In Viewer.kt, change the signature of onViewAttachedToWindow and onViewDetachedFromWindow to use android.view.View rather than android.view.View? because the former didn't compile with error "x does not implement y"
Other minor library updates

2022-11-05 17:10 UTC, romainguy requested changes

2022-11-05 17:10 UTC, romainguy commented on .gitattributes
> +* text=auto
Please don't change the .git files

2022-11-05 17:10 UTC, romainguy commented on .gitignore
> +filament/bin/matc.exe
Keep next to the other filament/bin

2022-11-05 17:10 UTC, romainguy commented on app/build.gradle
> +    implementation 'androidx.appcompat:appcompat:1.7.0-alpha01'
Why use an alpha here?

2022-11-05 17:10 UTC, romainguy commented on build.gradle
> +        classpath 'com.android.tools.build:gradle:8.0.0-alpha07'
Let's not depend on previews of Android Studio

2022-11-05 22:57 UTC, djnotes commented
Rolled things back to stable and other stuff

2022-11-06 20:46 UTC, romainguy approved these changes
Thank you!

2022-11-06 20:46 UTC, romainguy commented on .idea/codeStyles/Project.xml
> +<component name="ProjectCodeStyleConfiguration">
Please nuke this file. It's changing the code style settings for this project

2022-11-06 20:46 UTC, merged